import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import '@mantine/core/styles.css';
import DashboardLayout from "@/components/ui/dashboard-layout";
import { createTheme, MantineProvider } from '@mantine/core';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const theme = createTheme({
    /** Put your mantine theme override here */
  });
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        cz-shortcut-listen="true"
      >
        <MantineProvider theme={theme}>
          <DashboardLayout>
            {children}
          </DashboardLayout>
        </MantineProvider>
      </body>
    </html>
  );
}
